# Generated by Django 2.1.4 on 2019-10-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='profile',
            name='certs',
            field=models.FileField(default='', max_length=200, upload_to='files/certs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_of_study',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_qualification',
            field=models.CharField(choices=[('ssce', 'SSCE'), ('undergrad', 'Undergraduate'), ('postgrad', 'Postgraduate'), ('hnd', 'HND'), ('nd', 'ND/Diploma'), ('bsc', 'BSc'), ('ba', 'BA'), ('be', 'BE'), ('msc', 'MSc'), ('ma', 'MA'), ('m.ed', 'MEd'), ('mba', 'MBA'), ('phd', 'PhD')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='lga',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_address',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='ward',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(max_length=200, upload_to='files/'),
        ),
    ]
